spring:
    security:
        oauth2:
            client:
              registration:
                google:
                  client-id: 370837983438-u6etqmsaeshv413lfdp75r64spror834.apps.googleusercontent.com
                  client-secret: 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
                  scope:
                    - openid
                    - profile
                    - email

                naver:
                  client-id: ciCaC8mucupGzOi42uRf
                  client-secret: e_KU1obv89
                  authorization-grant-type: authorization_code
                  client-name: naver-clinet-app
                  redirect-uri: http://localhost:8080/login/oauth2/code/naver
                  scope: profile,email
                kakao:
                  client-id: 6bf41f71cebdb6a38a9f7336da4a9c8c
                  client-secret: Z6pZ5zrOwkEKupDuoKrWPW2iRVvoYKP7
                  authorization-grant-type: authorization_code
                  client-authentication-method: client_secret_post
                  client-name: client-app
                  redirect-uri: http://localhost:8080/login/oauth2/code/kakao
#                  scope: openid,profile_nickname,profile_image,account_email
#                  scope: profile_nickname,profile_image,account_email
                  scope: profile_nickname

              provider:
                naver:
                  authorization-uri: https://nid.naver.com/oauth2.0/authorize
                  token-uri: https://nid.naver.com/oauth2.0/token
                  user-info-uri: https://openapi.naver.com/v1/nid/me
                  user-name-attribute: response
                kakao:
                  # OpenID Connect ? ?? jwkSet URI ? ???? ?? ??? ????
                  issuer-uri: https://kauth.kakao.com
                  authorization-uri: https://kauth.kakao.com/oauth/authorize
                  token-uri: https://kauth.kakao.com/oauth/token
                  user-info-uri: https://kapi.kakao.com/v2/user/me
                  user-name-attribute: id # OpenID Connect ? ????? ???? ?? ??

    h2:
      console:
        enabled: true
        path: /h2-console

    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/coupon_db?characterEncoding=UTF-8&serverTimezone=UTC
      url: jdbc:mysql://localhost:3306?characterEncoding=UTF-8&serverTimezone=UTC
      username: cire
      password: 1234
    jpa:
      open-in-view: false
      properties:
        hibernate:
          ddl-auto: create
          default_batch_fetch_size: 100
          format_sql: false
          show_sql: false

    mvc:
      static-path-pattern: /static/**